# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "1b89fa8a9a973de95f603ec5c8243afc"
name = "Product Custom Option"
application_url = "https://patience-boat-jogging.ngrok-free.dev/appinstall/productcustomoption"
embedded = true
handle = "product-custom-option-apps-1"

[build]
dev_store_url = "product-custom-option-n8m2lukk.myshopify.com"

[webhooks]
api_version = "2025-10"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_files,write_files,read_metaobjects,write_metaobjects,read_products,write_products,read_cart_transforms,write_cart_transforms"
optional_scopes = [ ]
use_legacy_install_flow = false

[auth]
redirect_urls = [
  "https://patience-boat-jogging.ngrok-free.dev/auth/callback"
]

[app_proxy]
url = "https://patience-boat-jogging.ngrok-free.dev/api/proxy"
subpath = "test-app"
prefix = "apps"

[pos]
embedded = false
