api_version = "2026-07"

[[extensions]]
name = "t:name"
handle = "cart-transform-opt"
type = "function"
uid = "422de25c-6396-15bf-83e8-85933155f75e7380d3cb"
description = "t:description"

  [[extensions.targeting]]
  target = "cart.transform.run"
  input_query = "src/cart_transform_run.graphql"
  export = "cart-transform-run"

  [extensions.build]
  command = ""
  path = "dist/function.wasm"

  [extensions.ui.paths]
  create = "/"
  details = "/"
